/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignedOutRouteImport } from './routes/signed-out'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactSalesRouteImport } from './routes/contact-sales'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AccessDeniedRouteImport } from './routes/access-denied'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ErrorCodeRouteImport } from './routes/error.$code'
import { Route as DocsApiRouteImport } from './routes/docs.api'
import { Route as BlogSearchRouteImport } from './routes/blog.search'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedUpgradeRouteImport } from './routes/_authenticated/upgrade'
import { Route as AuthenticatedTeamRouteImport } from './routes/_authenticated/team'
import { Route as AuthenticatedSetupRouteImport } from './routes/_authenticated/setup'
import { Route as AuthenticatedRlsVerificationRouteImport } from './routes/_authenticated/rls-verification'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated/integrations'
import { Route as AuthenticatedGettingStartedRouteImport } from './routes/_authenticated/getting-started'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as BlogTagTagRouteImport } from './routes/blog.tag.$tag'
import { Route as BlogCategoryCategoryRouteImport } from './routes/blog.category.$category'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings.security'
import { Route as AuthenticatedSettingsEmailPreferencesRouteImport } from './routes/_authenticated/settings.email-preferences'
import { Route as AuthenticatedSettingsChangePasswordRouteImport } from './routes/_authenticated/settings.change-password'
import { Route as AuthenticatedInviteTokenRouteImport } from './routes/_authenticated/invite.$token'
import { Route as AuthenticatedIntegrationsWhatsappRouteImport } from './routes/_authenticated/integrations.whatsapp'
import { Route as AuthenticatedGettingStartedCompleteRouteImport } from './routes/_authenticated/getting-started.complete'
import { Route as AuthenticatedCheckoutStatusRouteImport } from './routes/_authenticated/checkout.status'
import { Route as AuthenticatedBillingStatementsRouteImport } from './routes/_authenticated/billing.statements'
import { Route as AuthenticatedAdminEmailRouteImport } from './routes/_authenticated/admin.email'
import { Route as ApiPublicWebhooksStripeRouteImport } from './routes/api/public/webhooks/stripe'
import { Route as ApiPublicWebhooksResendRouteImport } from './routes/api/public/webhooks.resend'
import { Route as ApiPublicWebhooksLemonsqueezyRouteImport } from './routes/api/public/webhooks/lemonsqueezy'
import { Route as ApiPublicHooksSuccessFeeMonthlyRouteImport } from './routes/api/public/hooks/success-fee-monthly'
import { Route as ApiPublicHooksRecoveryCadenceRouteImport } from './routes/api/public/hooks/recovery-cadence'
import { Route as AuthenticatedAdminEmailWebhooksRouteImport } from './routes/_authenticated/admin.email.webhooks'
import { Route as AuthenticatedAdminEmailSandboxRouteImport } from './routes/_authenticated/admin.email.sandbox'
import { Route as AuthenticatedAdminEmailPreviewRouteImport } from './routes/_authenticated/admin.email.preview'
import { Route as AuthenticatedAdminEmailDeliveriesRouteImport } from './routes/_authenticated/admin.email.deliveries'
import { Route as ApiPublicWebhooksProviderIntegrationIdRouteImport } from './routes/api/public/webhooks/$provider.$integrationId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignedOutRoute = SignedOutRouteImport.update({
  id: '/signed-out',
  path: '/signed-out',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactSalesRoute = ContactSalesRouteImport.update({
  id: '/contact-sales',
  path: '/contact-sales',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessDeniedRoute = AccessDeniedRouteImport.update({
  id: '/access-denied',
  path: '/access-denied',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ErrorCodeRoute = ErrorCodeRouteImport.update({
  id: '/error/$code',
  path: '/error/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DocsRoute,
} as any)
const BlogSearchRoute = BlogSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthenticatedUpgradeRoute = AuthenticatedUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamRoute = AuthenticatedTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSetupRoute = AuthenticatedSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRlsVerificationRoute =
  AuthenticatedRlsVerificationRouteImport.update({
    id: '/rls-verification',
    path: '/rls-verification',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGettingStartedRoute =
  AuthenticatedGettingStartedRouteImport.update({
    id: '/getting-started',
    path: '/getting-started',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const BlogTagTagRoute = BlogTagTagRouteImport.update({
  id: '/tag/$tag',
  path: '/tag/$tag',
  getParentRoute: () => BlogRoute,
} as any)
const BlogCategoryCategoryRoute = BlogCategoryCategoryRouteImport.update({
  id: '/category/$category',
  path: '/category/$category',
  getParentRoute: () => BlogRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/settings/security',
    path: '/settings/security',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsEmailPreferencesRoute =
  AuthenticatedSettingsEmailPreferencesRouteImport.update({
    id: '/settings/email-preferences',
    path: '/settings/email-preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsChangePasswordRoute =
  AuthenticatedSettingsChangePasswordRouteImport.update({
    id: '/settings/change-password',
    path: '/settings/change-password',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInviteTokenRoute =
  AuthenticatedInviteTokenRouteImport.update({
    id: '/invite/$token',
    path: '/invite/$token',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIntegrationsWhatsappRoute =
  AuthenticatedIntegrationsWhatsappRouteImport.update({
    id: '/whatsapp',
    path: '/whatsapp',
    getParentRoute: () => AuthenticatedIntegrationsRoute,
  } as any)
const AuthenticatedGettingStartedCompleteRoute =
  AuthenticatedGettingStartedCompleteRouteImport.update({
    id: '/complete',
    path: '/complete',
    getParentRoute: () => AuthenticatedGettingStartedRoute,
  } as any)
const AuthenticatedCheckoutStatusRoute =
  AuthenticatedCheckoutStatusRouteImport.update({
    id: '/status',
    path: '/status',
    getParentRoute: () => AuthenticatedCheckoutRoute,
  } as any)
const AuthenticatedBillingStatementsRoute =
  AuthenticatedBillingStatementsRouteImport.update({
    id: '/billing/statements',
    path: '/billing/statements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminEmailRoute = AuthenticatedAdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicWebhooksStripeRoute = ApiPublicWebhooksStripeRouteImport.update({
  id: '/api/public/webhooks/stripe',
  path: '/api/public/webhooks/stripe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksResendRoute = ApiPublicWebhooksResendRouteImport.update({
  id: '/api/public/webhooks/resend',
  path: '/api/public/webhooks/resend',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksLemonsqueezyRoute =
  ApiPublicWebhooksLemonsqueezyRouteImport.update({
    id: '/api/public/webhooks/lemonsqueezy',
    path: '/api/public/webhooks/lemonsqueezy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSuccessFeeMonthlyRoute =
  ApiPublicHooksSuccessFeeMonthlyRouteImport.update({
    id: '/api/public/hooks/success-fee-monthly',
    path: '/api/public/hooks/success-fee-monthly',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecoveryCadenceRoute =
  ApiPublicHooksRecoveryCadenceRouteImport.update({
    id: '/api/public/hooks/recovery-cadence',
    path: '/api/public/hooks/recovery-cadence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminEmailWebhooksRoute =
  AuthenticatedAdminEmailWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedAdminEmailRoute,
  } as any)
const AuthenticatedAdminEmailSandboxRoute =
  AuthenticatedAdminEmailSandboxRouteImport.update({
    id: '/sandbox',
    path: '/sandbox',
    getParentRoute: () => AuthenticatedAdminEmailRoute,
  } as any)
const AuthenticatedAdminEmailPreviewRoute =
  AuthenticatedAdminEmailPreviewRouteImport.update({
    id: '/preview',
    path: '/preview',
    getParentRoute: () => AuthenticatedAdminEmailRoute,
  } as any)
const AuthenticatedAdminEmailDeliveriesRoute =
  AuthenticatedAdminEmailDeliveriesRouteImport.update({
    id: '/deliveries',
    path: '/deliveries',
    getParentRoute: () => AuthenticatedAdminEmailRoute,
  } as any)
const ApiPublicWebhooksProviderIntegrationIdRoute =
  ApiPublicWebhooksProviderIntegrationIdRouteImport.update({
    id: '/api/public/webhooks/$provider/$integrationId',
    path: '/api/public/webhooks/$provider/$integrationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contact-sales': typeof ContactSalesRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/security': typeof SecurityRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signed-out': typeof SignedOutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app': typeof AuthenticatedAppRoute
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/events': typeof AuthenticatedEventsRoute
  '/getting-started': typeof AuthenticatedGettingStartedRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/team': typeof AuthenticatedTeamRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/docs/api': typeof DocsApiRoute
  '/error/$code': typeof ErrorCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/admin/email': typeof AuthenticatedAdminEmailRouteWithChildren
  '/billing/statements': typeof AuthenticatedBillingStatementsRoute
  '/checkout/status': typeof AuthenticatedCheckoutStatusRoute
  '/getting-started/complete': typeof AuthenticatedGettingStartedCompleteRoute
  '/integrations/whatsapp': typeof AuthenticatedIntegrationsWhatsappRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/email-preferences': typeof AuthenticatedSettingsEmailPreferencesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/admin/email/deliveries': typeof AuthenticatedAdminEmailDeliveriesRoute
  '/admin/email/preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/email/sandbox': typeof AuthenticatedAdminEmailSandboxRoute
  '/admin/email/webhooks': typeof AuthenticatedAdminEmailWebhooksRoute
  '/api/public/hooks/recovery-cadence': typeof ApiPublicHooksRecoveryCadenceRoute
  '/api/public/hooks/success-fee-monthly': typeof ApiPublicHooksSuccessFeeMonthlyRoute
  '/api/public/webhooks/lemonsqueezy': typeof ApiPublicWebhooksLemonsqueezyRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/$provider/$integrationId': typeof ApiPublicWebhooksProviderIntegrationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contact-sales': typeof ContactSalesRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/security': typeof SecurityRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signed-out': typeof SignedOutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/app': typeof AuthenticatedAppRoute
  '/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/events': typeof AuthenticatedEventsRoute
  '/getting-started': typeof AuthenticatedGettingStartedRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/setup': typeof AuthenticatedSetupRoute
  '/team': typeof AuthenticatedTeamRoute
  '/upgrade': typeof AuthenticatedUpgradeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/docs/api': typeof DocsApiRoute
  '/error/$code': typeof ErrorCodeRoute
  '/blog': typeof BlogIndexRoute
  '/admin/email': typeof AuthenticatedAdminEmailRouteWithChildren
  '/billing/statements': typeof AuthenticatedBillingStatementsRoute
  '/checkout/status': typeof AuthenticatedCheckoutStatusRoute
  '/getting-started/complete': typeof AuthenticatedGettingStartedCompleteRoute
  '/integrations/whatsapp': typeof AuthenticatedIntegrationsWhatsappRoute
  '/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/settings/email-preferences': typeof AuthenticatedSettingsEmailPreferencesRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/admin/email/deliveries': typeof AuthenticatedAdminEmailDeliveriesRoute
  '/admin/email/preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/admin/email/sandbox': typeof AuthenticatedAdminEmailSandboxRoute
  '/admin/email/webhooks': typeof AuthenticatedAdminEmailWebhooksRoute
  '/api/public/hooks/recovery-cadence': typeof ApiPublicHooksRecoveryCadenceRoute
  '/api/public/hooks/success-fee-monthly': typeof ApiPublicHooksSuccessFeeMonthlyRoute
  '/api/public/webhooks/lemonsqueezy': typeof ApiPublicWebhooksLemonsqueezyRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/$provider/$integrationId': typeof ApiPublicWebhooksProviderIntegrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/access-denied': typeof AccessDeniedRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/contact-sales': typeof ContactSalesRoute
  '/cookies': typeof CookiesRoute
  '/docs': typeof DocsRouteWithChildren
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/security': typeof SecurityRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signed-out': typeof SignedOutRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/status': typeof StatusRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRouteWithChildren
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/getting-started': typeof AuthenticatedGettingStartedRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/rls-verification': typeof AuthenticatedRlsVerificationRoute
  '/_authenticated/setup': typeof AuthenticatedSetupRoute
  '/_authenticated/team': typeof AuthenticatedTeamRoute
  '/_authenticated/upgrade': typeof AuthenticatedUpgradeRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/search': typeof BlogSearchRoute
  '/docs/api': typeof DocsApiRoute
  '/error/$code': typeof ErrorCodeRoute
  '/blog/': typeof BlogIndexRoute
  '/_authenticated/admin/email': typeof AuthenticatedAdminEmailRouteWithChildren
  '/_authenticated/billing/statements': typeof AuthenticatedBillingStatementsRoute
  '/_authenticated/checkout/status': typeof AuthenticatedCheckoutStatusRoute
  '/_authenticated/getting-started/complete': typeof AuthenticatedGettingStartedCompleteRoute
  '/_authenticated/integrations/whatsapp': typeof AuthenticatedIntegrationsWhatsappRoute
  '/_authenticated/invite/$token': typeof AuthenticatedInviteTokenRoute
  '/_authenticated/settings/change-password': typeof AuthenticatedSettingsChangePasswordRoute
  '/_authenticated/settings/email-preferences': typeof AuthenticatedSettingsEmailPreferencesRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/blog/category/$category': typeof BlogCategoryCategoryRoute
  '/blog/tag/$tag': typeof BlogTagTagRoute
  '/_authenticated/admin/email/deliveries': typeof AuthenticatedAdminEmailDeliveriesRoute
  '/_authenticated/admin/email/preview': typeof AuthenticatedAdminEmailPreviewRoute
  '/_authenticated/admin/email/sandbox': typeof AuthenticatedAdminEmailSandboxRoute
  '/_authenticated/admin/email/webhooks': typeof AuthenticatedAdminEmailWebhooksRoute
  '/api/public/hooks/recovery-cadence': typeof ApiPublicHooksRecoveryCadenceRoute
  '/api/public/hooks/success-fee-monthly': typeof ApiPublicHooksSuccessFeeMonthlyRoute
  '/api/public/webhooks/lemonsqueezy': typeof ApiPublicWebhooksLemonsqueezyRoute
  '/api/public/webhooks/resend': typeof ApiPublicWebhooksResendRoute
  '/api/public/webhooks/stripe': typeof ApiPublicWebhooksStripeRoute
  '/api/public/webhooks/$provider/$integrationId': typeof ApiPublicWebhooksProviderIntegrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access-denied'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/contact-sales'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/rss.xml'
    | '/security'
    | '/session-expired'
    | '/signed-out'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin'
    | '/analytics'
    | '/app'
    | '/checkout'
    | '/events'
    | '/getting-started'
    | '/integrations'
    | '/notifications'
    | '/onboarding'
    | '/rls-verification'
    | '/setup'
    | '/team'
    | '/upgrade'
    | '/blog/$slug'
    | '/blog/search'
    | '/docs/api'
    | '/error/$code'
    | '/blog/'
    | '/admin/email'
    | '/billing/statements'
    | '/checkout/status'
    | '/getting-started/complete'
    | '/integrations/whatsapp'
    | '/invite/$token'
    | '/settings/change-password'
    | '/settings/email-preferences'
    | '/settings/security'
    | '/api/public/health'
    | '/blog/category/$category'
    | '/blog/tag/$tag'
    | '/admin/email/deliveries'
    | '/admin/email/preview'
    | '/admin/email/sandbox'
    | '/admin/email/webhooks'
    | '/api/public/hooks/recovery-cadence'
    | '/api/public/hooks/success-fee-monthly'
    | '/api/public/webhooks/lemonsqueezy'
    | '/api/public/webhooks/resend'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/$provider/$integrationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access-denied'
    | '/auth'
    | '/careers'
    | '/contact'
    | '/contact-sales'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/rss.xml'
    | '/security'
    | '/session-expired'
    | '/signed-out'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/admin'
    | '/analytics'
    | '/app'
    | '/checkout'
    | '/events'
    | '/getting-started'
    | '/integrations'
    | '/notifications'
    | '/onboarding'
    | '/rls-verification'
    | '/setup'
    | '/team'
    | '/upgrade'
    | '/blog/$slug'
    | '/blog/search'
    | '/docs/api'
    | '/error/$code'
    | '/blog'
    | '/admin/email'
    | '/billing/statements'
    | '/checkout/status'
    | '/getting-started/complete'
    | '/integrations/whatsapp'
    | '/invite/$token'
    | '/settings/change-password'
    | '/settings/email-preferences'
    | '/settings/security'
    | '/api/public/health'
    | '/blog/category/$category'
    | '/blog/tag/$tag'
    | '/admin/email/deliveries'
    | '/admin/email/preview'
    | '/admin/email/sandbox'
    | '/admin/email/webhooks'
    | '/api/public/hooks/recovery-cadence'
    | '/api/public/hooks/success-fee-monthly'
    | '/api/public/webhooks/lemonsqueezy'
    | '/api/public/webhooks/resend'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/$provider/$integrationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/access-denied'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/contact-sales'
    | '/cookies'
    | '/docs'
    | '/faq'
    | '/features'
    | '/forgot-password'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/rss.xml'
    | '/security'
    | '/session-expired'
    | '/signed-out'
    | '/sitemap.xml'
    | '/status'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/app'
    | '/_authenticated/checkout'
    | '/_authenticated/events'
    | '/_authenticated/getting-started'
    | '/_authenticated/integrations'
    | '/_authenticated/notifications'
    | '/_authenticated/onboarding'
    | '/_authenticated/rls-verification'
    | '/_authenticated/setup'
    | '/_authenticated/team'
    | '/_authenticated/upgrade'
    | '/blog/$slug'
    | '/blog/search'
    | '/docs/api'
    | '/error/$code'
    | '/blog/'
    | '/_authenticated/admin/email'
    | '/_authenticated/billing/statements'
    | '/_authenticated/checkout/status'
    | '/_authenticated/getting-started/complete'
    | '/_authenticated/integrations/whatsapp'
    | '/_authenticated/invite/$token'
    | '/_authenticated/settings/change-password'
    | '/_authenticated/settings/email-preferences'
    | '/_authenticated/settings/security'
    | '/api/public/health'
    | '/blog/category/$category'
    | '/blog/tag/$tag'
    | '/_authenticated/admin/email/deliveries'
    | '/_authenticated/admin/email/preview'
    | '/_authenticated/admin/email/sandbox'
    | '/_authenticated/admin/email/webhooks'
    | '/api/public/hooks/recovery-cadence'
    | '/api/public/hooks/success-fee-monthly'
    | '/api/public/webhooks/lemonsqueezy'
    | '/api/public/webhooks/resend'
    | '/api/public/webhooks/stripe'
    | '/api/public/webhooks/$provider/$integrationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccessDeniedRoute: typeof AccessDeniedRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  ContactSalesRoute: typeof ContactSalesRoute
  CookiesRoute: typeof CookiesRoute
  DocsRoute: typeof DocsRouteWithChildren
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SecurityRoute: typeof SecurityRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SignedOutRoute: typeof SignedOutRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StatusRoute: typeof StatusRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ErrorCodeRoute: typeof ErrorCodeRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksRecoveryCadenceRoute: typeof ApiPublicHooksRecoveryCadenceRoute
  ApiPublicHooksSuccessFeeMonthlyRoute: typeof ApiPublicHooksSuccessFeeMonthlyRoute
  ApiPublicWebhooksLemonsqueezyRoute: typeof ApiPublicWebhooksLemonsqueezyRoute
  ApiPublicWebhooksResendRoute: typeof ApiPublicWebhooksResendRoute
  ApiPublicWebhooksStripeRoute: typeof ApiPublicWebhooksStripeRoute
  ApiPublicWebhooksProviderIntegrationIdRoute: typeof ApiPublicWebhooksProviderIntegrationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signed-out': {
      id: '/signed-out'
      path: '/signed-out'
      fullPath: '/signed-out'
      preLoaderRoute: typeof SignedOutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-sales': {
      id: '/contact-sales'
      path: '/contact-sales'
      fullPath: '/contact-sales'
      preLoaderRoute: typeof ContactSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-denied': {
      id: '/access-denied'
      path: '/access-denied'
      fullPath: '/access-denied'
      preLoaderRoute: typeof AccessDeniedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/error/$code': {
      id: '/error/$code'
      path: '/error/$code'
      fullPath: '/error/$code'
      preLoaderRoute: typeof ErrorCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof DocsRoute
    }
    '/blog/search': {
      id: '/blog/search'
      path: '/search'
      fullPath: '/blog/search'
      preLoaderRoute: typeof BlogSearchRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/_authenticated/upgrade': {
      id: '/_authenticated/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AuthenticatedUpgradeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/team': {
      id: '/_authenticated/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthenticatedTeamRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/setup': {
      id: '/_authenticated/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AuthenticatedSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rls-verification': {
      id: '/_authenticated/rls-verification'
      path: '/rls-verification'
      fullPath: '/rls-verification'
      preLoaderRoute: typeof AuthenticatedRlsVerificationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getting-started': {
      id: '/_authenticated/getting-started'
      path: '/getting-started'
      fullPath: '/getting-started'
      preLoaderRoute: typeof AuthenticatedGettingStartedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/blog/tag/$tag': {
      id: '/blog/tag/$tag'
      path: '/tag/$tag'
      fullPath: '/blog/tag/$tag'
      preLoaderRoute: typeof BlogTagTagRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/category/$category': {
      id: '/blog/category/$category'
      path: '/category/$category'
      fullPath: '/blog/category/$category'
      preLoaderRoute: typeof BlogCategoryCategoryRouteImport
      parentRoute: typeof BlogRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/email-preferences': {
      id: '/_authenticated/settings/email-preferences'
      path: '/settings/email-preferences'
      fullPath: '/settings/email-preferences'
      preLoaderRoute: typeof AuthenticatedSettingsEmailPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/change-password': {
      id: '/_authenticated/settings/change-password'
      path: '/settings/change-password'
      fullPath: '/settings/change-password'
      preLoaderRoute: typeof AuthenticatedSettingsChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invite/$token': {
      id: '/_authenticated/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof AuthenticatedInviteTokenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/integrations/whatsapp': {
      id: '/_authenticated/integrations/whatsapp'
      path: '/whatsapp'
      fullPath: '/integrations/whatsapp'
      preLoaderRoute: typeof AuthenticatedIntegrationsWhatsappRouteImport
      parentRoute: typeof AuthenticatedIntegrationsRoute
    }
    '/_authenticated/getting-started/complete': {
      id: '/_authenticated/getting-started/complete'
      path: '/complete'
      fullPath: '/getting-started/complete'
      preLoaderRoute: typeof AuthenticatedGettingStartedCompleteRouteImport
      parentRoute: typeof AuthenticatedGettingStartedRoute
    }
    '/_authenticated/checkout/status': {
      id: '/_authenticated/checkout/status'
      path: '/status'
      fullPath: '/checkout/status'
      preLoaderRoute: typeof AuthenticatedCheckoutStatusRouteImport
      parentRoute: typeof AuthenticatedCheckoutRoute
    }
    '/_authenticated/billing/statements': {
      id: '/_authenticated/billing/statements'
      path: '/billing/statements'
      fullPath: '/billing/statements'
      preLoaderRoute: typeof AuthenticatedBillingStatementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/email': {
      id: '/_authenticated/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AuthenticatedAdminEmailRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/webhooks/stripe': {
      id: '/api/public/webhooks/stripe'
      path: '/api/public/webhooks/stripe'
      fullPath: '/api/public/webhooks/stripe'
      preLoaderRoute: typeof ApiPublicWebhooksStripeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/resend': {
      id: '/api/public/webhooks/resend'
      path: '/api/public/webhooks/resend'
      fullPath: '/api/public/webhooks/resend'
      preLoaderRoute: typeof ApiPublicWebhooksResendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/lemonsqueezy': {
      id: '/api/public/webhooks/lemonsqueezy'
      path: '/api/public/webhooks/lemonsqueezy'
      fullPath: '/api/public/webhooks/lemonsqueezy'
      preLoaderRoute: typeof ApiPublicWebhooksLemonsqueezyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/success-fee-monthly': {
      id: '/api/public/hooks/success-fee-monthly'
      path: '/api/public/hooks/success-fee-monthly'
      fullPath: '/api/public/hooks/success-fee-monthly'
      preLoaderRoute: typeof ApiPublicHooksSuccessFeeMonthlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recovery-cadence': {
      id: '/api/public/hooks/recovery-cadence'
      path: '/api/public/hooks/recovery-cadence'
      fullPath: '/api/public/hooks/recovery-cadence'
      preLoaderRoute: typeof ApiPublicHooksRecoveryCadenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/email/webhooks': {
      id: '/_authenticated/admin/email/webhooks'
      path: '/webhooks'
      fullPath: '/admin/email/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminEmailWebhooksRouteImport
      parentRoute: typeof AuthenticatedAdminEmailRoute
    }
    '/_authenticated/admin/email/sandbox': {
      id: '/_authenticated/admin/email/sandbox'
      path: '/sandbox'
      fullPath: '/admin/email/sandbox'
      preLoaderRoute: typeof AuthenticatedAdminEmailSandboxRouteImport
      parentRoute: typeof AuthenticatedAdminEmailRoute
    }
    '/_authenticated/admin/email/preview': {
      id: '/_authenticated/admin/email/preview'
      path: '/preview'
      fullPath: '/admin/email/preview'
      preLoaderRoute: typeof AuthenticatedAdminEmailPreviewRouteImport
      parentRoute: typeof AuthenticatedAdminEmailRoute
    }
    '/_authenticated/admin/email/deliveries': {
      id: '/_authenticated/admin/email/deliveries'
      path: '/deliveries'
      fullPath: '/admin/email/deliveries'
      preLoaderRoute: typeof AuthenticatedAdminEmailDeliveriesRouteImport
      parentRoute: typeof AuthenticatedAdminEmailRoute
    }
    '/api/public/webhooks/$provider/$integrationId': {
      id: '/api/public/webhooks/$provider/$integrationId'
      path: '/api/public/webhooks/$provider/$integrationId'
      fullPath: '/api/public/webhooks/$provider/$integrationId'
      preLoaderRoute: typeof ApiPublicWebhooksProviderIntegrationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminEmailRouteChildren {
  AuthenticatedAdminEmailDeliveriesRoute: typeof AuthenticatedAdminEmailDeliveriesRoute
  AuthenticatedAdminEmailPreviewRoute: typeof AuthenticatedAdminEmailPreviewRoute
  AuthenticatedAdminEmailSandboxRoute: typeof AuthenticatedAdminEmailSandboxRoute
  AuthenticatedAdminEmailWebhooksRoute: typeof AuthenticatedAdminEmailWebhooksRoute
}

const AuthenticatedAdminEmailRouteChildren: AuthenticatedAdminEmailRouteChildren =
  {
    AuthenticatedAdminEmailDeliveriesRoute:
      AuthenticatedAdminEmailDeliveriesRoute,
    AuthenticatedAdminEmailPreviewRoute: AuthenticatedAdminEmailPreviewRoute,
    AuthenticatedAdminEmailSandboxRoute: AuthenticatedAdminEmailSandboxRoute,
    AuthenticatedAdminEmailWebhooksRoute: AuthenticatedAdminEmailWebhooksRoute,
  }

const AuthenticatedAdminEmailRouteWithChildren =
  AuthenticatedAdminEmailRoute._addFileChildren(
    AuthenticatedAdminEmailRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminEmailRoute: typeof AuthenticatedAdminEmailRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminEmailRoute: AuthenticatedAdminEmailRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCheckoutRouteChildren {
  AuthenticatedCheckoutStatusRoute: typeof AuthenticatedCheckoutStatusRoute
}

const AuthenticatedCheckoutRouteChildren: AuthenticatedCheckoutRouteChildren = {
  AuthenticatedCheckoutStatusRoute: AuthenticatedCheckoutStatusRoute,
}

const AuthenticatedCheckoutRouteWithChildren =
  AuthenticatedCheckoutRoute._addFileChildren(
    AuthenticatedCheckoutRouteChildren,
  )

interface AuthenticatedGettingStartedRouteChildren {
  AuthenticatedGettingStartedCompleteRoute: typeof AuthenticatedGettingStartedCompleteRoute
}

const AuthenticatedGettingStartedRouteChildren: AuthenticatedGettingStartedRouteChildren =
  {
    AuthenticatedGettingStartedCompleteRoute:
      AuthenticatedGettingStartedCompleteRoute,
  }

const AuthenticatedGettingStartedRouteWithChildren =
  AuthenticatedGettingStartedRoute._addFileChildren(
    AuthenticatedGettingStartedRouteChildren,
  )

interface AuthenticatedIntegrationsRouteChildren {
  AuthenticatedIntegrationsWhatsappRoute: typeof AuthenticatedIntegrationsWhatsappRoute
}

const AuthenticatedIntegrationsRouteChildren: AuthenticatedIntegrationsRouteChildren =
  {
    AuthenticatedIntegrationsWhatsappRoute:
      AuthenticatedIntegrationsWhatsappRoute,
  }

const AuthenticatedIntegrationsRouteWithChildren =
  AuthenticatedIntegrationsRoute._addFileChildren(
    AuthenticatedIntegrationsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRouteWithChildren
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedGettingStartedRoute: typeof AuthenticatedGettingStartedRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRouteWithChildren
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRlsVerificationRoute: typeof AuthenticatedRlsVerificationRoute
  AuthenticatedSetupRoute: typeof AuthenticatedSetupRoute
  AuthenticatedTeamRoute: typeof AuthenticatedTeamRoute
  AuthenticatedUpgradeRoute: typeof AuthenticatedUpgradeRoute
  AuthenticatedBillingStatementsRoute: typeof AuthenticatedBillingStatementsRoute
  AuthenticatedInviteTokenRoute: typeof AuthenticatedInviteTokenRoute
  AuthenticatedSettingsChangePasswordRoute: typeof AuthenticatedSettingsChangePasswordRoute
  AuthenticatedSettingsEmailPreferencesRoute: typeof AuthenticatedSettingsEmailPreferencesRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRouteWithChildren,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedGettingStartedRoute:
    AuthenticatedGettingStartedRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRouteWithChildren,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRlsVerificationRoute: AuthenticatedRlsVerificationRoute,
  AuthenticatedSetupRoute: AuthenticatedSetupRoute,
  AuthenticatedTeamRoute: AuthenticatedTeamRoute,
  AuthenticatedUpgradeRoute: AuthenticatedUpgradeRoute,
  AuthenticatedBillingStatementsRoute: AuthenticatedBillingStatementsRoute,
  AuthenticatedInviteTokenRoute: AuthenticatedInviteTokenRoute,
  AuthenticatedSettingsChangePasswordRoute:
    AuthenticatedSettingsChangePasswordRoute,
  AuthenticatedSettingsEmailPreferencesRoute:
    AuthenticatedSettingsEmailPreferencesRoute,
  AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogSearchRoute: typeof BlogSearchRoute
  BlogIndexRoute: typeof BlogIndexRoute
  BlogCategoryCategoryRoute: typeof BlogCategoryCategoryRoute
  BlogTagTagRoute: typeof BlogTagTagRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogSearchRoute: BlogSearchRoute,
  BlogIndexRoute: BlogIndexRoute,
  BlogCategoryCategoryRoute: BlogCategoryCategoryRoute,
  BlogTagTagRoute: BlogTagTagRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DocsRouteChildren {
  DocsApiRoute: typeof DocsApiRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsApiRoute: DocsApiRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AccessDeniedRoute: AccessDeniedRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  ContactSalesRoute: ContactSalesRoute,
  CookiesRoute: CookiesRoute,
  DocsRoute: DocsRouteWithChildren,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SecurityRoute: SecurityRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SignedOutRoute: SignedOutRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StatusRoute: StatusRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ErrorCodeRoute: ErrorCodeRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksRecoveryCadenceRoute: ApiPublicHooksRecoveryCadenceRoute,
  ApiPublicHooksSuccessFeeMonthlyRoute: ApiPublicHooksSuccessFeeMonthlyRoute,
  ApiPublicWebhooksLemonsqueezyRoute: ApiPublicWebhooksLemonsqueezyRoute,
  ApiPublicWebhooksResendRoute: ApiPublicWebhooksResendRoute,
  ApiPublicWebhooksStripeRoute: ApiPublicWebhooksStripeRoute,
  ApiPublicWebhooksProviderIntegrationIdRoute:
    ApiPublicWebhooksProviderIntegrationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
